name: Playwright Tests
on: #Quando vai rodar?
  push:
    branches: [ main, master ] #Quando tiver um push na main ou na master
  pull_request:                # ou
    branches: [ main, master ] #Quando tiver um pull request na main ou na master
jobs: #Tarefas que devem ser executadas
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  #define quem que vai rodar os testes
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30  #Reter os relatórios por 30 dias
